"""initial

Revision ID: 022c45207184
Revises: 
Create Date: 2023-08-24 17:41:03.854749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022c45207184'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data_lat', sa.String(), nullable=True),
    sa.Column('data_lon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('degrees_Celsius', sa.Integer(), nullable=True),
    sa.Column('day', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_day'), 'weather', ['day'], unique=False)
    op.create_index(op.f('ix_weather_degrees_Celsius'), 'weather', ['degrees_Celsius'], unique=False)
    op.create_index(op.f('ix_weather_id'), 'weather', ['id'], unique=False)
    op.create_table('crons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crons_id'), 'crons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crons_id'), table_name='crons')
    op.drop_table('crons')
    op.drop_index(op.f('ix_weather_id'), table_name='weather')
    op.drop_index(op.f('ix_weather_degrees_Celsius'), table_name='weather')
    op.drop_index(op.f('ix_weather_day'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
